apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "devops-workflow.fullname" . }}
  labels:
    {{- include "devops-workflow.labels" . | nindent 4 }}
spec:
  serviceName: { { include "devops-workflow.fullname" . } }
    podManagementPolicy: { { .Values.podManagementPolicy } }
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "devops-workflow.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "devops-workflow.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "devops-workflow.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: MY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: credentials
                  key: password
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: "/config"
              readOnly: true
            - name: { { .Values.statefulSet.name } }
              mountPath: /app_volume/
            - name: workdir
              mountPath: /workdir/
      volumes:
        - name: config
          configMap:
            name: devopslab-configmap
        - name: workdir
          emptyDir: { }
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        - name: install
          image: busybox
          command:
            - wget
            - "-O"
            - "/workdir/index.html"
            - http://info.cern.ch
          volumeMounts:
            - name: workdir
              mountPath: "/workdir"
        dnsPolicy: Default
  volumeClaimTemplates:
    - metadata:
        name: {{ .Values.statefulSet.name }}
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ .Values.statefulSet.storageSize }}