# Initial config from official repo
# https://github.com/grafana/loki/blob/main/clients/cmd/promtail/promtail-local-config.yaml

# JSON/RegEx config from https://gist.github.com/ruanbekker/c6fa9bc6882e6f324b4319c5e3622460

server:
  http_listen_port: 9080
  grpc_listen_port: 0

client:
  url: http://loki:3100/api/prom/push

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
        - localhost
        labels:
          job: varlogs
          __path__: /var/log/*log

  - job_name: containers
    
    static_configs:
    - targets:
        - localhost
      labels:
        job: containerlogs
        __path__: /var/lib/docker/containers/*/*log

    pipeline_stages:
      - json:
          expressions:
            stream: stream
            attrs: attrs
            tag: attrs.tag

      - regex:
          expression: (?P<image_name>(?:[^|]*[^|])).(?P<container_name>(?:[^|]*[^|])).(?P<image_id>(?:[^|]*[^|])).(?P<container_id>(?:[^|]*[^|]))
          source: "tag"

      - labels:
          tag:
          stream:
          image_name:
          container_name:
          image_id:
          container_id: