version: "3"

volumes:
  app_volume:

networks:
  loki:

services:
  loki:
    image: grafana/loki:2.5.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki

  promtail:
    image: grafana/promtail:2.5.0
    volumes:
      - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yml
    networks:
      - loki

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - loki

  prometheus:
    image: "prom/prometheus:v2.36.1"
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command: --config.file=/etc/prometheus/prometheus.yml
    networks:
      - loki
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: 500M
   
  python_app:
    container_name: python_app
    image: nyahonk/devops_course:latest
    command: runserver 0.0.0.0:8000

    volumes:
      - app_volume:/app_volume
    expose:
      - 8000
    ports:
      - "8000:8000"
    networks:
      - loki
    labels:
      org.label-schema.group: "python_app"

