version: '3.9'
services:
  telltime:
    image: telltime:latest
    container_name: telltime
    build:
      context: app_python/
      dockerfile: Dockerfile
    command: python3 -m app
    ports:
      - '8080:8080'
    healthcheck:
      test: curl --fail http://localhost:8080/api/v1/health || exit 1
      interval: 10s
      timeout: 10s
      start_period: 10s
      retries: 2
