# -*- mode: ruby -*-
# vi: set ft=ruby :

servers=[
  {
    :hostname => "server-1",
    :box => "ubuntu/trusty64",
    :ip => "192.168.50.101",
    :ram => 1024,
    :cpu => 2
  },
  {
    :hostname => "server-2",
    :box => "ubuntu/trusty64",
    :ip => "192.168.50.102",
    :ram => 1024,
    :cpu => 4
  },
  {
    :hostname => "server-3",
    :box => "ubuntu/trusty64",
    :ip => "192.168.50.103",
    :ram => 1024,
    :cpu => 4
  }
]

Vagrant.configure("2") do |config|
  servers.each do |machine|
      config.vm.define machine[:hostname] do |node|
          node.vm.box = machine[:box]
          node.vm.hostname = machine[:hostname]
          node.vm.network "private_network", ip: machine[:ip]
          node.vm.provider "virtualbox" do |vb|
              vb.customize ["modifyvm", :id, "--memory", machine[:ram]]
          end

          node.vm.provision "ansible" do |ansible|
            ansible.playbook = "../app_python/terraform.yml"
          end
      end
  end
end