# -*- mode: ruby -*-
# vi: set ft=ruby :

nodes = [
  { :hostname => 'alpha',   :ip => '192.168.56.2', :box => 'ubuntu/focal64', :ram => '256'},
  { :hostname => 'bravo',   :ip => '192.168.56.3', :box => 'ubuntu/focal64', :ram => '256'},
  { :hostname => 'charlie', :ip => '192.168.56.4', :box => 'ubuntu/focal64', :ram => '256'},
]

Vagrant.configure("2") do |config|
  nodes.each do |node|
    config.vm.define node[:hostname] do |nodeconfig|
      nodeconfig.vm.box = node[:box]
      nodeconfig.vm.hostname = node[:hostname]
      nodeconfig.vm.network :private_network, ip: node[:ip]

      nodeconfig.vm.provider :virtualbox do |vb|
        vb.memory = node[:ram]
      end

    end
  end
end
