Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-16.04"
  config.vm.network "private_network", ip: "192.168.33.10"
  (1..3).each do |i|
		# Defining VM properties
		config.vm.define "lab4_vm#{i}" do |node|
			# Specifying the provider as VirtualBox and naming the VM's
			node.vm.provider "virtualbox" do |n|
				# The VM will be named as lab4_vm{i}
        n.gui = true
				n.name = "lab4_vm#{i}"  
			end
		end
	end
end
