# -*- mode: ruby -*-
# vi: set ft=ruby :

servers=[
  {
    :hostname => "server_1",
    :box => "ubuntu/trusty64",
    :ram => 1024,
    :cpu => 2
  },
  {
    :hostname => "server_2",
    :box => "ubuntu/trusty64",
    :ram => 1024,
    :cpu => 4
  },
  {
    :hostname => "server_3",
    :box => "ubuntu/trusty64",
    :ram => 1024,
    :cpu => 4
  }
]

Vagrant.configure("2") do |config|
  servers.each do |machine|
      config.vm.define machine[:hostname] do |node|
          node.vm.box = machine[:box]
          node.vm.hostname = machine[:hostname] 
          node.vm.network "private_network", type: "dhcp"
          node.vm.provider "virtualbox" do |vb|
              vb.customize ["modifyvm", :id, "--memory", machine[:ram]]
          end

          node.vm.provision "ansible" do |ansible|
            ansible.playbook = "env_creator.yml"
          end
      end
  end
end 