nodes = [
  { :hostname => 'vagrant1',   :ip => '192.168.56.10', :box => 'vagrant1_box' },
  { :hostname => 'vagrant2',   :ip => '192.168.56.11', :box => 'vagrant2_box' },
  { :hostname => 'vagrant3',   :ip => '192.168.56.12', :box => 'vagrant3_box' },
]

Vagrant.configure("2") do |config|
  nodes.each do |node|
    config.vm.define node[:hostname] do |nodeconfig|
      nodeconfig.vm.box = "hashicorp/bionic64"
      nodeconfig.vm.hostname = node[:hostname] + ".box"
      nodeconfig.vm.network :private_network, ip: node[:ip]

      nodeconfig.vm.provider :virtualbox do |vb|
        vb.memory = "256"
      end
    end
  end
end