version: '3.9'

services:
  app:
    image: willsem/moscow-local-time:latest
    container_name: monitoring-app
    restart: unless-stopped
    ports:
       - '5000:5000'
    networks:
      - monitoring-net
    logging:
      driver: 'json-file'
      options:
        max-size: '100m'
        tag: '{{.ImageName}}'


  grafana:
    image: grafana/grafana:9.0.0
    container_name: monitoring-grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    networks:
      - monitoring-net
    logging:
      driver: 'json-file'
      options:
        max-size: '100m'
        max-file: '3'
        tag: '{{.ImageName}}'


  promtail:
    image: grafana/promtail:2.5.0
    container_name: monitoring-promtail
    restart: unless-stopped
    ports:
      - '9080:9080'
    volumes:
      - /var/log:/var/log
      - /var/lib/docker/containers/:/var/lib/docker/containers
      - ./promtail.yaml:/etc/promtail/promtail.yaml
    command:
      - '-config.file=/etc/promtail/promtail.yaml'
    networks:
      - monitoring-net
    logging:
      driver: 'json-file'
      options:
        max-size: '100m'
        max-file: '3'
        tag: '{{.ImageName}}'


  loki:
    image: grafana/loki:2.5.0
    container_name: monitoring-loki
    restart: unless-stopped
    ports:
      - '3100:3100'
    command:
      - '-config.file=/etc/loki/local-config.yaml'
    networks:
      - monitoring-net
    logging:
      driver: 'json-file'
      options:
        max-size: '100m'
        max-file: '3'
        tag: '{{.ImageName}}'


networks:
  monitoring-net:
