apiVersion: v1
kind: ConfigMap
metadata:
  name: sherlock-config
  namespace: default
data:
  {{-/* Note, indent of only two spaces */}}
  config.json: |-
{{ .Files.Get "files/config.json" | indent 4 }}
{{/* .Get, not .Glob; indent 4 spaces, more than 2 above */}}