apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-lab-app-deployment
  labels:
    app: app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: devops-labs
        image: behouba/dev_ops_labs:latest
        ports:
        - containerPort: 5000