apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-python-deployment
  labels:
    app: app-python
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-python
  template:
    metadata:
      labels:
        app: app-python
    spec:
      containers:
      - name: app-python
        image: ananasness/iu-devops-labs:laba2
        command: ["uwsgi"]
        args: ["--http", ":8000", "--module", "django_project.wsgi"]
        ports: 
        - containerPort: 8000
        
