apiVersion: v1
kind: Service
metadata:
  name: flutter-app-service
  labels:
    app: flutter-app
spec:
  type: LoadBalancer
  selector:
    app: flutter-app
  ports:
    - protocol: TCP
      port: 8080