apiVersion: apps/v1
kind: Deployment
metadata:
  name: flutter-app-deployment
  labels:
    app: flutter-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flutter-app
  template:
    metadata:
      labels:
        app: flutter-app
    spec:
      containers:
      - name: flutter-app
        image: elbatanony/devops-flutter
        ports:
        - containerPort: 8080