password: ENC[AES256_GCM,data:gU8m1WDH1Gkdgg==,iv:4OSUQcK6XGoW/slaxxA8ifDUresJX62hHCzXsgnbno4=,tag:zjSQ7PRM8W0HlfbLOUd4og==,type:str]
sops:
    kms: []
    gcp_kms: []
    lastmodified: '2022-07-22T14:20:31Z'
    mac: ENC[AES256_GCM,data:u/OAmRGyQn1SfBZNrtTJMXrwq/8WHolFhiZRzLha+yKYPBg7OgoEq76guEZwEmST193yWVAVfaji00VRSmn93gaC45tmhEBPxUqUAoqvPCI88vqT+OpgIwBQcRHffwM62WlYtKWxG34JsVHSvsA9b7bpPrI+Ak9Vz/5sD6riFPA=,iv:srwKIrKiFgYtTYuvME1/b95MGlkvBFMf/vZQkUYi6gk=,tag:1NbICDZyHdyyuhW/pwvW9g==,type:str]
    pgp:
    -   created_at: '2022-07-22T14:18:58Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA7mNbxLsXQHQAQv5AUmj4vHmg6UzSOP/9GwTTszI8RjxdLLAziFh6iaRI2TF
            rf6OmKpEaTd9KgLprMr/x6bzjYEQcQ4VBXkJS7+GlZgBCbdpk0jFEaWmc19gbl0O
            42q5ljfE8vJkezR/Xwv5M+360AszroTjSntNGwtIE+3kFFwwtzNgl+M/jMY3ytag
            F4FRNJnpJKNW6lb5q60JFyBM4/ybdWtv1JFOS0NvyEJFLFKYZuGu+Pdcau+2/H9U
            ID7KW7u9VXzPwBNVjq2XTVJsbVtVU5co9Xh286GnvmaBaqrFAN085soxzAR9dciA
            7y3cNt943LjKFIUd9M6orYRLAWyM0XWoPMb1ZSdbELwjJSmmdE2Qu80Lu3SO3A5p
            Y7J+0AzgecpugVsOeKDqHO/lce0ZOO4Madt93Ql47ozRl8EoH/bljvc/mXZh6FSc
            UyWwfLjPQx78xPsm/bYBbpdW8zPL1dV4pBYgfMy/MvQ5Vj/6DSQggo41dPyc++Ju
            u5mn6e0IBEZUIhqXkEFy0l4ByhK6vfSjd0VPlMoixZt2kJEPb2aLeE39c6pGP/F9
            cg3eWZo2JWuntb1RgU8Y0CZI8LJWo+glDEtkDINRPKOiunyKkCJVV5oLvlCMUGU2
            AE5BZjdPKxIYSJnA6T3m
            =aHWU
            -----END PGP MESSAGE-----
        fp: E00F87660B4E516542E76D42C4A75AF11F6E711A
    unencrypted_suffix: _unencrypted
    version: 3.0.3
