apiVersion: apps/v1

kind: StatefulSet

metadata:
  name: time-python

spec:
  serviceName: "time-python"

  replicas: 3

  selector:
    matchLabels:
      app: time-python

  template:
    metadata:
      labels:
        app: time-python

    spec:
      containers:
        - name: time-python
          image: raminafandi/time-python:time-python
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 5000

  volumeClaimTemplates:
    - metadata:
        name: www

      spec:
        accessModes: ["ReadWriteOnce"]

        resources:
          requests:
            storage: 1Gi
