---
- name: Docker pull image
  docker_container:
    name: devops_course
    state: started
    image: "nyahonk/devops_course:latest"
    pull: true
    expose:
      - 8000
    ports:
      - "0.0.0.0:8000:8000"
