apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ include "python-app.fullname" . }}-configmap
    labels:
      app: {{ include "python-app.fullname" . }}
      chart: {{ include "python-app.chart" . }}
data:
  config.json:
    '{{ .Files.Get "files/config.json"}}'