apiVersion: v1
kind: Service
metadata:
  name: devopslab-deployment-service
  labels:
    app: app
spec:
  type: LoadBalancer
  selector:
    app: app
  ports:
    - name: http
      protocol: TCP
      port: 7000
      targetPort: 8000
