---
- name: Install pip
  become: true
  package:
    name: "python3-pip"
    state: present

- name: Install docker library
  become: true
  pip:
    name: "docker"
    state: present

- name: Run a container
  become: true
  docker_container:
    name: app_python
    image: "heivory/devops-lab"
    state: started
    ports: "5000:5000"