name: FastAPI CI/CD

on: push

jobs:
  # build_and_test:
  #   name: Build and run Unit Testing
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Set up Python 3.8
  #     uses: actions/setup-python@v1
  #     with:
  #       python-version: 3.8
  #   - name: Install dependencies
  #     run: |
  #       python -m pip install --upgrade pip
  #       cd app_python
  #       pip install -r requirements.txt
  #   - name: Test with pytest
  #     run: ./app_python/test.sh

  docker_build_and_push:
    name: Build Image
    # needs: build_and_test
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
    steps:
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v2
      - name: Build
        run: docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} ./app_python/
      - name: Push
        run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}