name: Django CI

on:
  push:
    branches: [master, lab3]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Tests
        run: |
          echo SECRET_KEY=${{secrets.SECRET_KEY}} >> .env
          cd app_python
          python manage.py test
