name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

defaults:
  run:
    working-directory: ./app_python


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USER_NAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
          context: ./app_python
          file: ./app_python/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USER_NAME }}/django_docker_image:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USER_NAME }}/django_docker_image:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USER_NAME }}/django_docker_image:buildcache,mode=max
          
    - name: Run tests
      run: docker-compose up --exit-code-from test --build --remove-orphans test
