#main.yml
#This workflow will install Python dependencies, lint using Black, run tests using Pytest 
#and Deploy the FastAPI app to Heroku
name: fastapi-github-actions-test

on: 
  #Trigger the workflow on a push event to the master branch only
  push: 
    branches: [master]

#A workflow job running sequentially
jobs:
  build:
    #runs-on: defines The workflow runner
    runs-on: ubuntu-latest 
    #steps: defines a series of tasks executed by the Job
    steps:
    - uses: actions/checkout@v2
    - run: |   # To fetch all history for all tags and branches
        git fetch --prune --unshallow  

    #Task for setting up Python 3.10 using actions/setup-python@v2 Github action
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10' # Modify python version HERE
        cache: 'pip'

    #Task for installing dependencies, multi-line command
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install black pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    #Task for adding black linter   
    - name: Lint with black
      run: |
        # Code formatting with black, check every python file in the src directory 
        black src
        black --check src
    # Task for testing with pytest
    - name: Test with pytest
      run: |
        pytest
    # Building and pushing docker image
    - name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: fahima2019/lab2
        tags: lab2
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
