name: Python testing

on:
  push:
    paths:
      - "app_python/**"

jobs:

  unit-tests:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: app_python

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Run unit tests
        run: pytest app_test.py