name: Python app CI
author: raghadsalameh1

on:
  push:
    branches: [ lab3 ]
  pull_request:
    branches: [ lab3 ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        python -m pip install --upgrade pip
        if [ -f app_python/requirements.txt ]; then pip install -r app_python/requirements.txt; fi
        pip install -e app_python/.
    - name: Lint with pylint
      run: |
        pylint app_python/src --disable=E0401,E0601
        pylint app_python/tests --disable=E0401,E0601
    - name: Test with pytest
      run: |
        pytest
    - name: Prepare build file for Dockerfile
      run: |
        mkdir ./app_python/build
        cp -r ./app_python/src ./app_python/build/src
        cp -r ./app_python/tests ./app_python/build/tests
        cp ./app_python/setup.py ./app_python/build/setup.py
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: ./app_python
        push: true
        tags: raghadsy/repo_2
