name: Python testing

on:
  push:
    paths:
      - ".github/workflows/python-ci.yml"
      - "app_python/**"

jobs:

  unit-tests:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: app_python

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Run unit tests
        run: pytest app_test.py
  
  build-image:
    needs: unit-tests

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: app_python

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: elbatanony
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: ${{ runner.os }}-buildx-
      
      - name: Build image and push to Docker Hub
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: app_python/
          file: app_python/Dockerfile
          push: true
          tags: elbatanony/devops-python:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache