name: QA build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

defaults:
  run:
    working-directory: ./app_python

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build docker
      run: docker build . --tag test_build_app_python

    - name: Check code with flake8
      run: docker-compose up --exit-code-from check_django_project --build --remove-orphans check_django_project

    - name: Run tests
      run: docker-compose up --exit-code-from test_django_project --build --remove-orphans test_django_project
