name: Workflow
on: [push, pull_request]

jobs:
  linter:
    name: Linter 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          pip3 install -U pip
          pip3 install -r requirements.txt
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Lint with pylint
        run: |
          pip3 install pylint
          pylint .
      - name: Lint with black
        run: |
          pip3 install black
          black .
      - name: Lint with isort
        run: |
          pip3 install isort
          isort .
      - name: Lint with pycodestyle
        run: |
          pip3 install pycodestyle
          pycodestyle .
      - name: Lint with mypy
        run: |
          pip3 install mypy
          mypy .

  test:
    name: Test 
    runs-on: ubuntu-18.04
    needs: linter

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          pip3 install -U pip
          pip3 install -r requirements.txt
      - name: Run test
        run: |
          python3 app_test.py

  publish:
    name: Publish 
    runs-on: ubuntu-18.04
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/devops-lab:latest
          
